### PR TITLE
Quick fix to add back track quality for tracks produced by new KF

### PR DESCRIPTION
**Pull request by Jingyan95**
@tschuh

### CODE REVIEW

**Comment by tschuh** [comment]
there is a space too much in front of trkMVA3. That code change would pass the trkMVA values produced by tracklet pattern reco to the KF output, is that what you want?

**Comment by Jingyan95** [comment]
> there is a space too much in front of trkMVA3. That code change would pass the trkMVA values produced by tracklet pattern reco to the KF output, is that what you want?

OK, I just realized the track quality here is produced by tracklet with raw parameter. We need track quality produced by fitted parameters.

**Comment by tschuh** [comment]
Did we not have that in the past? Got that lost during the merge from cmssw 11 to 12?

**Comment by Jingyan95** [comment]
> Did we not have that in the past? Got that lost during the merge from cmssw 11 to 12?

I was looking at the old ntuples I produced with cmssw 11 and I didn't see trk_MVA1 being filled. I would assume track quality has been missing from KFout tracks since the beginning?

**Comment by tschuh** [comment]
that may be, but somehow this is ringing a bell in my mind.

**Pull request closed without merging**
