### PR TITLE
L1 tk dev 11 2 0 pre6 vmlutfix

### PR DESCRIPTION
**Pull request by djcranshaw**
#### PR description:

Updates the emulator version to allow the VMRouter LUTs to be printed for use in HLS

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by tomalin** [comment]
I've checked that the new code writes out the LUT data files VMR_*_finebin.tab, VMTableInner*.tab & VMTableOuter*.tab .
@djcranshaw I do notice that it doesn't write out VMTableOuterD1.tab (or D2 or D4), which were in the .tar data file you gave to Mei-Li for her HLS. Is this is mistake?

**Comment by djcranshaw** [comment]
> I've checked that the new code writes out the LUT data files VMR___finebin.tab, VMTableInner_.tab & VMTableOuter*.tab .
> @djcranshaw I do notice that it doesn't write out VMTableOuterD1.tab (or D2 or D4), which were in the .tar data file you gave to Mei-Li for her HLS. Is this is mistake?

Yes, thanks for spotting. There is a typo with '=' instead of '+' here https://github.com/cms-L1TK/cmssw/pull/36/files#diff-adf66cf9f1b95d0cc672d481f87c40eeR128. Fixing now.

**Review by tomalin — APPROVED** [review]
I've run the code and checked it produces the required output LUT tables.
Regarding coding style, it appears that that the first two auto coding style checks from https://twiki.cern.ch/twiki/bin/view/CMS/L1TrackCodeRules have not been run on this PR, but it also looks like they were forgotten in previous PRs. So this time, its probably best if we fix this style via a separate PR.

**Comment by djcranshaw** [comment]
@tomalin So apparently even after your accepted review I'm not allowed to merge the pull request, only those with write access can do that.

**Comment by tomalin** [comment]
@djcranshaw @skinnari Derek, somehow you need to register for the git team https://github.com/orgs/cms-L1TK/teams/l1tkexperts in order to merge PR requests.

**Pull request merged**
