### PR TITLE
fix of KFin EnableTruncation option.

### PR DESCRIPTION
**Pull request by tschuh**
bug fix

### CODE REVIEW

**Review by Jingyan95 — APPROVED** [review]
The truncation issue is fixed with this change.

**Review by Jingyan95 — CHANGES_REQUESTED** [review]
The truncation "false" issue is fixed but a new bug arises.
I got a segmentation violation when I set truncation to "True".

**Comment by tschuh** [comment]
upsi

**Review by tomalin — APPROVED** [review]
approved

**Comment by tomalin** [comment]
> approved

@tschuh you need to respond to Jack's comment, so github knows you have addressed all reviewers comments.

**Review by Jingyan95 — APPROVED** [review]

**Comment by Jingyan95** [comment]
OK, I have varified the commit.

**Pull request merged**
