### PR TITLE
Reduce MC to 104 iterations

### PR DESCRIPTION
**Pull request by bryates**
#### PR description:

This PR fixes the agreement with the HLS implementation of the MatchCalculator by dropping the number of iterations to 104.

#### PR validation:

We noticed a single `FullMatch` in event 43 was missing in the HLS implementation:
```
Event: 43
FullMatch 1:
index	reference	computed
0	0x620922b00301a	0x620922b00301a
1	0x622129c5f91c6	0x622129c5f91c6
2	0x64090f15f31b1	0x64090f15f31b1
3	0x640d0f15f3186	0x640d0f15f3186
4	0x641d2d39fb031	0x641d2d39fb031
5	0x64212d39fc1cc	0x0	<=== missing
```
```
@E Simulation failed: Function 'main' returns nonzero value '1'.
ERROR: [SIM 211-100] 'csim_design' failed: nonzero return value.
INFO: [SIM 211-3] *************** CSIM finish ***************
```

After recreating the test vectors with this PR, we see full agreement:
```
Event: 43
FullMatch 1:
index   reference       computed
0       0x620922b00301a 0x620922b00301a
1       0x622129c5f91c6 0x622129c5f91c6
2       0x64090f15f31b1 0x64090f15f31b1
3       0x640d0f15f3186 0x640d0f15f3186
4       0x641d2d39fb031 0x641d2d39fb031
```
```
INFO: [SIM 211-1] CSim done with 0 errors.
INFO: [SIM 211-3] *************** CSIM finish ***************
```

This is the **only** event that changes.

### CODE REVIEW

**Review by tomalin — APPROVED** [review]
Approved to fix disagreement with HLS code

**Comment by tomalin** [comment]
@bryates github is saying above your code has conflicts. Perhaps you didn't start from the latest cms-L1TK:L1TK-dev-12_0_0_pre4 ?

**Comment by bryates** [comment]
> @bryates github is saying above your code has conflicts. Perhaps you didn't start from the latest cms-L1TK:L1TK-dev-12_0_0_pre4 ?

My mistake, I used `L1TK-dev-12_0_0_pre4` instead of `cms-L1TK/L1TK-dev-12_0_0_pre4`. I just rebased and pushed.

**Comment by bryates** [comment]
@tomalin It looks like the CI failed. Is this because I used a fork? The CMSSW instructions indicated to use a fork, but I can just push a branch to this repo instead.

**Comment by tomalin** [comment]
You must put your branch in cms-L1TK, not your personal repo, or CI will fail due to access rights.

**Comment by bryates** [comment]
Closing this PR since it was made on my fork.

**Pull request closed without merging**
