### PR TITLE
MC/MP LUTs

### PR DESCRIPTION
**Pull request by bryates**
#### PR description:

This PR additional LUTs required for the MC/MP disk HLS implementation in [PR #242](https://github.com/cms-L1TK/firmware-hls/pull/242).
`alpha inner/outer` - LUT for disk 2S detector corrections
`rSS inner/outer` - LUT for disk 2S r values.

#### PR validation:

With this PR we see full agreement in all MC disks (modulo some debugging).

### CODE REVIEW

**Comment by tomalin** [comment]
Please explain the the Description of the PR what the new LUT tables are. And also which PR to the HLS repo causes them to be read in by the HLS code.

**Comment by bryates** [comment]
> Please explain the the Description of the PR what the new LUT tables are. And also which PR to the HLS repo causes them to be read in by the HLS code.

Done.

**Comment by tomalin** [comment]
Would you mind adding:
1) A comment to the top of TrackletLUT.h, explaining what this class is for.
2) I believe that each type in enum TrackletLUT::VMRTableType represents a different LUT? If so, could you add a comment to the declaration of this enum briefly indicating the meaning of each LUT type?

**Comment by bryates** [comment]
> Would you mind adding:
> 
> 1. A comment to the top of TrackletLUT.h, explaining what this class is for.
> 2. I believe that each type in enum TrackletLUT::VMRTableType represents a different LUT? If so, could you add a comment to the declaration of this enum briefly indicating the meaning of each LUT type?

I've added some comments.

**Review by tomalin — APPROVED** [review]
Looks fine to me, except that @bryates needs to run "scram b -j8 code-format" to avoid the PR failing CI tests.

@aryd , do you have any objections to us merging this?

**Comment by bryates** [comment]
> Looks fine to me, except that @bryates needs to run "scram b -j8 code-format" to avoid the PR failing CI tests.
> 
> @aryd , do you have any objections to us merging this?

Just in case it was missed, I've pushed the code format changes. I think we're just waiting in any feedback from @aryd before merging.

**Pull request merged**
